Name: Configure_Datastore_to_SQL_Basic_setup_RT_1124
Type: ProjectFolder
Children:
- Name: BranchingEnabled
  Type: BaseDataVariableType
  DataType: Boolean
  Value: false
- Name: PasswordPolicy
  Type: PasswordPolicy
  Children:
  - Name: MaximumPasswordAge
    Type: PropertyType
    DataType: UInt16
    Value: 0
  - Name: EnforcePasswordHistory
    Type: PropertyType
    DataType: Byte
    Value: 1
  - Name: MinimumPasswordAge
    Type: PropertyType
    DataType: UInt16
    Value: 0
  - Name: MinimumPasswordLength
    Type: PropertyType
    DataType: Byte
    Value: 8
- Name: Locales
  Type: BaseDataVariableType
  DataType: String
  ValueRank: OneDimension
  ArrayDimensions: [0]
  Value: ["en-US"]
- Name: LocaleFallbackList
  Type: BaseDataVariableType
  DataType: String
  ValueRank: OneDimension
  ArrayDimensions: [0]
  Value: ["en-US"]
- File: UI/UI.yaml
- File: Model/Model.yaml
- File: Converters/Converters.yaml
- File: Alarms/Alarms.yaml
- File: Recipes/Recipes.yaml
- File: Loggers/Loggers.yaml
- File: DataStores/DataStores.yaml
- File: Reports/Reports.yaml
- File: 'OPC-UA/OPC-UA.yaml'
- File: CommDrivers/CommDrivers.yaml
- File: NetLogic/NetLogic.yaml
- File: Security/Security.yaml
- File: Translations/Translations.yaml
- File: Retentivity/Retentivity.yaml
- Name: DefaultUserFolder
  Type: NodePointer
  DataType: NodeId
  Value: {"IdType":2,"Id":"c49910682f592ab2fd6ceab3bc6fdeca","Namespace":7}
  Children:
  - Name: Kind
    Type: PropertyType
    DataType: NodeId
    Value: {"Id":61}
